//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class APTCustomer
    {
        public string SAPcustcode { get; set; }
        public string SAPCustomerName { get; set; }
        public string SAPsalesorg { get; set; }
        public string SAPdistchannel { get; set; }
        public string SAPDivision { get; set; }
        public string SAPblock_code { get; set; }
        public string CusttomerCustcode { get; set; }
        public string CusttomerCustname { get; set; }
        public string SalesGroup { get; set; }
        public string SalesGroupDesc { get; set; }
        public string CustomerGroup { get; set; }
        public string CustGroupName { get; set; }
        public string CustomerGroup1 { get; set; }
        public string CustGroupName1 { get; set; }
        public string CustomerGroup2 { get; set; }
        public string CustGroupName2 { get; set; }
        public string AccountName { get; set; }
        public string Shortname { get; set; }
    }
}
