//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class APTDbContext : DbContext
    {
        public APTDbContext()
            : base("name=APTDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoleClaim> AspNetRoleClaims { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AspNetUserToken> AspNetUserTokens { get; set; }
        public virtual DbSet<PersistedGrant> PersistedGrants { get; set; }
        public virtual DbSet<TB_M_ACTIVITY> TB_M_ACTIVITY { get; set; }
        public virtual DbSet<TB_M_BRAND> TB_M_BRAND { get; set; }
        public virtual DbSet<TB_M_BUDGET_TYPE> TB_M_BUDGET_TYPE { get; set; }
        public virtual DbSet<TB_M_CHANNEL> TB_M_CHANNEL { get; set; }
        public virtual DbSet<TB_M_CLIENT> TB_M_CLIENT { get; set; }
        public virtual DbSet<TB_M_COMPANY> TB_M_COMPANY { get; set; }
        public virtual DbSet<TB_M_COST_CENTER> TB_M_COST_CENTER { get; set; }
        public virtual DbSet<TB_M_CUSTOMER> TB_M_CUSTOMER { get; set; }
        public virtual DbSet<TB_M_DISTRIBUTOR> TB_M_DISTRIBUTOR { get; set; }
        public virtual DbSet<TB_M_DOCUMENT_TYPE> TB_M_DOCUMENT_TYPE { get; set; }
        public virtual DbSet<TB_M_EMISSION> TB_M_EMISSION { get; set; }
        public virtual DbSet<TB_M_EMPLOYEE> TB_M_EMPLOYEE { get; set; }
        public virtual DbSet<TB_M_FISCAL_YEAR> TB_M_FISCAL_YEAR { get; set; }
        public virtual DbSet<TB_M_GL_ACCOUNT> TB_M_GL_ACCOUNT { get; set; }
        public virtual DbSet<TB_M_GL_GROUP> TB_M_GL_GROUP { get; set; }
        public virtual DbSet<TB_M_HOLIDAY> TB_M_HOLIDAY { get; set; }
        public virtual DbSet<TB_M_INTERNAL_ORDER> TB_M_INTERNAL_ORDER { get; set; }
        public virtual DbSet<TB_M_ORGANIZATION> TB_M_ORGANIZATION { get; set; }
        public virtual DbSet<TB_M_PACK> TB_M_PACK { get; set; }
        public virtual DbSet<TB_M_PRODUCT> TB_M_PRODUCT { get; set; }
        public virtual DbSet<TB_M_PROMOTION_GROUP> TB_M_PROMOTION_GROUP { get; set; }
        public virtual DbSet<TB_M_PROMOTION_PLAN_TYPE> TB_M_PROMOTION_PLAN_TYPE { get; set; }
        public virtual DbSet<TB_M_SIZE> TB_M_SIZE { get; set; }
        public virtual DbSet<TB_M_SOURCE_FUND> TB_M_SOURCE_FUND { get; set; }
        public virtual DbSet<TB_M_UNIT> TB_M_UNIT { get; set; }
        public virtual DbSet<TB_M_VENDOR> TB_M_VENDOR { get; set; }
        public virtual DbSet<TB_P_BRAND_ORG> TB_P_BRAND_ORG { get; set; }
        public virtual DbSet<TB_P_COST_IO> TB_P_COST_IO { get; set; }
        public virtual DbSet<TB_P_CUSTOMER_PARTY> TB_P_CUSTOMER_PARTY { get; set; }
        public virtual DbSet<TB_P_EMP_CHANNEL> TB_P_EMP_CHANNEL { get; set; }
        public virtual DbSet<TB_P_EMP_ORG> TB_P_EMP_ORG { get; set; }
        public virtual DbSet<TB_P_PRODUCT_GROUP> TB_P_PRODUCT_GROUP { get; set; }
        public virtual DbSet<TB_T_BILLING> TB_T_BILLING { get; set; }
        public virtual DbSet<TB_T_BUDGET_D> TB_T_BUDGET_D { get; set; }
        public virtual DbSet<TB_T_BUDGET_H> TB_T_BUDGET_H { get; set; }
        public virtual DbSet<TB_T_CLAIM_D> TB_T_CLAIM_D { get; set; }
        public virtual DbSet<TB_T_CLAIM_H> TB_T_CLAIM_H { get; set; }
        public virtual DbSet<TB_T_CREDIT_NOTE> TB_T_CREDIT_NOTE { get; set; }
        public virtual DbSet<TB_T_DEBIT_NOTE> TB_T_DEBIT_NOTE { get; set; }
        public virtual DbSet<TB_T_DOCUMENT> TB_T_DOCUMENT { get; set; }
        public virtual DbSet<TB_T_FIXED_CONTRACT_D> TB_T_FIXED_CONTRACT_D { get; set; }
        public virtual DbSet<TB_T_FIXED_CONTRACT_H> TB_T_FIXED_CONTRACT_H { get; set; }
        public virtual DbSet<TB_T_PROMOTION_PLAN_D> TB_T_PROMOTION_PLAN_D { get; set; }
        public virtual DbSet<TB_T_PROMOTION_PLAN_H> TB_T_PROMOTION_PLAN_H { get; set; }
        public virtual DbSet<TB_WM_FLOW_ITEM> TB_WM_FLOW_ITEM { get; set; }
        public virtual DbSet<TB_WM_OPERATION> TB_WM_OPERATION { get; set; }
        public virtual DbSet<TB_WM_WORKFLOW> TB_WM_WORKFLOW { get; set; }
        public virtual DbSet<TB_WM_WORKFLOW_STATE> TB_WM_WORKFLOW_STATE { get; set; }
        public virtual DbSet<TB_WP_STATE_ACTOR> TB_WP_STATE_ACTOR { get; set; }
        public virtual DbSet<TB_WP_STATE_DIRECTION> TB_WP_STATE_DIRECTION { get; set; }
        public virtual DbSet<DB_Errors> DB_Errors { get; set; }
        public virtual DbSet<TB_M_PACK_20210923> TB_M_PACK_20210923 { get; set; }
        public virtual DbSet<TB_S_EMPLOYEE> TB_S_EMPLOYEE { get; set; }
        public virtual DbSet<TB_S_ORGANIZATION> TB_S_ORGANIZATION { get; set; }
    
        public virtual int Daily_Job_TB_M_ACTIVITY()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Daily_Job_TB_M_ACTIVITY");
        }
    
        public virtual int Daily_Job_TB_M_BRAND()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Daily_Job_TB_M_BRAND");
        }
    
        public virtual int Daily_Job_TB_M_CHANNEL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Daily_Job_TB_M_CHANNEL");
        }
    
        public virtual int Daily_Job_TB_M_CLIENT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Daily_Job_TB_M_CLIENT");
        }
    
        public virtual int Daily_Job_TB_M_COST_CENTER()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Daily_Job_TB_M_COST_CENTER");
        }
    
        public virtual int Daily_Job_TB_M_CUSTOMER()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Daily_Job_TB_M_CUSTOMER");
        }
    
        public virtual int Daily_Job_TB_M_GL_ACCOUNT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Daily_Job_TB_M_GL_ACCOUNT");
        }
    
        public virtual int Daily_Job_TB_M_PACK()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Daily_Job_TB_M_PACK");
        }
    
        public virtual int Daily_Job_TB_M_PRODUCT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Daily_Job_TB_M_PRODUCT");
        }
    
        public virtual int Daily_Job_TB_M_SIZE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Daily_Job_TB_M_SIZE");
        }
    
        public virtual int Daily_Job_TB_M_VENDOR()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Daily_Job_TB_M_VENDOR");
        }
    
        [DbFunction("APTDbContext", "Split")]
        public virtual IQueryable<string> Split(string @string, string delimiter)
        {
            var stringParameter = @string != null ?
                new ObjectParameter("String", @string) :
                new ObjectParameter("String", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[APTDbContext].[Split](@String, @Delimiter)", stringParameter, delimiterParameter);
        }
    
        public virtual int SP_SYNC_ORGANIZATION()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SYNC_ORGANIZATION");
        }
    
        public virtual ObjectResult<string> SP_GENERATE_DOC_CODE(string dOC_TYPE_CODE, Nullable<int> dOC_YEAR, Nullable<int> dOC_MONTH)
        {
            var dOC_TYPE_CODEParameter = dOC_TYPE_CODE != null ?
                new ObjectParameter("DOC_TYPE_CODE", dOC_TYPE_CODE) :
                new ObjectParameter("DOC_TYPE_CODE", typeof(string));
    
            var dOC_YEARParameter = dOC_YEAR.HasValue ?
                new ObjectParameter("DOC_YEAR", dOC_YEAR) :
                new ObjectParameter("DOC_YEAR", typeof(int));
    
            var dOC_MONTHParameter = dOC_MONTH.HasValue ?
                new ObjectParameter("DOC_MONTH", dOC_MONTH) :
                new ObjectParameter("DOC_MONTH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_GENERATE_DOC_CODE", dOC_TYPE_CODEParameter, dOC_YEARParameter, dOC_MONTHParameter);
        }
    }
}
