//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget
    {
        public int BudgetId { get; set; }
        public Nullable<int> DocumentId { get; set; }
        public Nullable<int> BudgetTypeId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<decimal> ActualLastYear { get; set; }
        public decimal BudgetValue { get; set; }
        public Nullable<decimal> BudgetTargetInYear { get; set; }
        public Nullable<decimal> PercentContribution { get; set; }
        public Nullable<decimal> SaleInvesment { get; set; }
        public Nullable<int> CostCenterId { get; set; }
        public string CenterName { get; set; }
        public Nullable<int> SourceFundId { get; set; }
        public string FundName { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual BudgetType BudgetType { get; set; }
        public virtual CostCenter CostCenter { get; set; }
        public virtual Document Document { get; set; }
        public virtual SourceFund SourceFund { get; set; }
    }
}
