//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostCenter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CostCenter()
        {
            this.Budgets = new HashSet<Budget>();
            this.FixedContracts = new HashSet<FixedContract>();
        }
    
        public int CostCenterId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> SourceFundId { get; set; }
        public string CenterCode { get; set; }
        public string CenterName { get; set; }
        public string Site { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Budget> Budgets { get; set; }
        public virtual Company Company { get; set; }
        public virtual SourceFund SourceFund { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FixedContract> FixedContracts { get; set; }
    }
}
