//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerProduct
    {
        public int CustomerProductId { get; set; }
        public int CustomerId { get; set; }
        public int ProductCategoryId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
