//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.Budgets = new HashSet<Budget>();
            this.DocumentActions = new HashSet<DocumentAction>();
            this.FixedContracts = new HashSet<FixedContract>();
            this.SaleForecasts = new HashSet<SaleForecast>();
        }
    
        public int DocumentId { get; set; }
        public Nullable<int> DocumentTypeId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> ChannelId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string DocumentTypeCode { get; set; }
        public Nullable<int> DocumentYear { get; set; }
        public Nullable<int> DocumentMonth { get; set; }
        public string ReferenceNo { get; set; }
        public string ClientCode { get; set; }
        public string ClientName { get; set; }
        public string ChannelCode { get; set; }
        public string ChannelName { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public Nullable<decimal> TotalSale { get; set; }
        public Nullable<decimal> TotalInvestment { get; set; }
        public int Version { get; set; }
        public int Revision { get; set; }
        public int CurrentStateId { get; set; }
        public string CurrentState { get; set; }
        public int NextStateId { get; set; }
        public string NextState { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Budget> Budgets { get; set; }
        public virtual Channel Channel { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual DocumentType DocumentType { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentAction> DocumentActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FixedContract> FixedContracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleForecast> SaleForecasts { get; set; }
    }
}
