//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentAction
    {
        public int DocumentActionId { get; set; }
        public Nullable<int> DocumentId { get; set; }
        public Nullable<int> ActorId { get; set; }
        public string ActorName { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string Comment { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual Document Document { get; set; }
    }
}
