//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixedContract
    {
        public Nullable<int> BrandId { get; set; }
        public int FixedContractId { get; set; }
        public Nullable<int> DocumentId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> CostCenterId { get; set; }
        public Nullable<int> TradeInvesmentId { get; set; }
        public string ConditionType { get; set; }
        public string ContractCategory { get; set; }
        public string ContractDesc { get; set; }
        public string UOM { get; set; }
        public string DateRefForm { get; set; }
        public Nullable<decimal> M01JAN { get; set; }
        public Nullable<decimal> M02FEB { get; set; }
        public Nullable<decimal> M03MAR { get; set; }
        public Nullable<decimal> M04APR { get; set; }
        public Nullable<decimal> M05MAY { get; set; }
        public Nullable<decimal> M06JUN { get; set; }
        public Nullable<decimal> M07JUL { get; set; }
        public Nullable<decimal> M08AUG { get; set; }
        public Nullable<decimal> M09SEP { get; set; }
        public Nullable<decimal> M10OCT { get; set; }
        public Nullable<decimal> M11NOV { get; set; }
        public Nullable<decimal> M12DEC { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual CostCenter CostCenter { get; set; }
        public virtual Document Document { get; set; }
        public virtual GLAccount GLAccount { get; set; }
        public virtual TradeInvesment TradeInvesment { get; set; }
    }
}
