//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateProcess
    {
        public int StateProcessId { get; set; }
        public int WorkflowStateId { get; set; }
        public int ActionId { get; set; }
        public int ActivityId { get; set; }
        public string ActivityCode { get; set; }
        public string ActionCode { get; set; }
        public string ActivityName { get; set; }
        public string ActionName { get; set; }
        public int ActivityPiority { get; set; }
        public int ActionPiority { get; set; }
    
        public virtual WorkflowAction WorkflowAction { get; set; }
        public virtual WorkflowActivity WorkflowActivity { get; set; }
        public virtual WorkflowState WorkflowState { get; set; }
    }
}
