//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_ACTIVITY
    {
        public int ACTIVITY_ID { get; set; }
        public Nullable<int> ACC_ID { get; set; }
        public string ACTIVITY_CODE { get; set; }
        public string ACTIVITY_TYPE { get; set; }
        public string ACTIVTITY_NAME { get; set; }
        public string HAS_FIXED_CONTRACT { get; set; }
        public string CAN_DEDUCTABLE { get; set; }
        public string IN_THB_CS { get; set; }
        public string IN_GROSS_SALE { get; set; }
        public string IN_NOT_SALE { get; set; }
        public string OUT_THB_CS { get; set; }
        public string OUT_GROSS_SALE { get; set; }
        public string OUT_NOT_SALE { get; set; }
        public string NO_RELATE_ABS_AMT { get; set; }
        public string VALUABLE { get; set; }
        public string ACTIVITY_DESC { get; set; }
        public string FLAG_ROW { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    
        public virtual TB_M_GL_ACCOUNT TB_M_GL_ACCOUNT { get; set; }
    }
}
