//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_GL_ACCOUNT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_M_GL_ACCOUNT()
        {
            this.TB_M_ACTIVITY = new HashSet<TB_M_ACTIVITY>();
            this.TB_P_CUSTOMER_PARTY = new HashSet<TB_P_CUSTOMER_PARTY>();
        }
    
        public int ACC_ID { get; set; }
        public Nullable<int> IO_ID { get; set; }
        public Nullable<int> CENTER_ID { get; set; }
        public Nullable<int> FUND_ID { get; set; }
        public Nullable<int> FUND_CENTER_ID { get; set; }
        public string ACC_CODE { get; set; }
        public string ACC_NAME { get; set; }
        public string ACC_TYPE { get; set; }
        public string ACC_TYPE_DESC { get; set; }
        public string ACC_GROUP1 { get; set; }
        public string ACC_GROUP1_DESC { get; set; }
        public string ACC_GROUP2 { get; set; }
        public string ACC_GROUP2_DESC { get; set; }
        public string ACC_REMARK { get; set; }
        public string FLAG_ROW { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_M_ACTIVITY> TB_M_ACTIVITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_P_CUSTOMER_PARTY> TB_P_CUSTOMER_PARTY { get; set; }
    }
}
