//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Collections.Generic;

    public partial class TBL_M_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_M_Product()
        {
          //  this.SaleForecasts = new HashSet<SaleForecast>();
        }

        public int ProductId { get; set; }
        public int ProductCategoryId { get; set; }
        public int BrandId { get; set; }
        public string BrandCode { get; set; }
        public string ProductCategoryName { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string SKU { get; set; }
        public string Color { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Height { get; set; }
        public string Shape { get; set; }
        public string Size { get; set; }
        public Nullable<int> QTY { get; set; }
        public string UOM { get; set; }
        public Nullable<decimal> LTP { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }

   
    }
}
