//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_ORGANIZATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_M_ORGANIZATION()
        {
            this.TB_M_ORGANIZATION1 = new HashSet<TB_M_ORGANIZATION>();
            this.TB_P_BRAND_ORG = new HashSet<TB_P_BRAND_ORG>();
            this.TB_P_EMP_ORG = new HashSet<TB_P_EMP_ORG>();
        }
    
        public string ORG_CODE { get; set; }
        public string REPORT_TO { get; set; }
        public string COMP_CODE { get; set; }
        public string HIERACHY_ID { get; set; }
        public string ORG_NAME { get; set; }
        public string ORG_ABBR { get; set; }
        public string ORG_DESC { get; set; }
        public string FLAG_ORG { get; set; }
        public string FLAG_ROW { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    
        public virtual TB_M_COMPANY TB_M_COMPANY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_M_ORGANIZATION> TB_M_ORGANIZATION1 { get; set; }
        public virtual TB_M_ORGANIZATION TB_M_ORGANIZATION2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_P_BRAND_ORG> TB_P_BRAND_ORG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_P_EMP_ORG> TB_P_EMP_ORG { get; set; }
    }
}
