//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_ORGANIZATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_M_ORGANIZATION()
        {
            this.TB_P_COST_IO = new HashSet<TB_P_COST_IO>();
        }
    
        public int ORG_ID { get; set; }
        public Nullable<int> COMP_ID { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_DEPARTMENT_NAME { get; set; }
        public string ORG_POSITION_NAME { get; set; }
        public string ORG_DESC { get; set; }
        public string FLAG_ROW { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    
        public virtual TB_M_COMPANY TB_M_COMPANY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_P_COST_IO> TB_P_COST_IO { get; set; }
    }
}
