//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_P_COST_IO
    {
        public int CENTER_ID { get; set; }
        public int IO_ID { get; set; }
        public int ORG_ID { get; set; }
        public string FLAG_ROW { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    
        public virtual TB_M_COST_CENTER TB_M_COST_CENTER { get; set; }
        public virtual TB_M_INTERNAL_ORDER TB_M_INTERNAL_ORDER { get; set; }
        public virtual TB_M_ORGANIZATION TB_M_ORGANIZATION { get; set; }
    }
}
