//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_S_ORGANIZATION
    {
        public string COMP_CODE { get; set; }
        public string ORG_CODE { get; set; }
        public string REPORT_TO { get; set; }
        public string HIERACHY_ID { get; set; }
        public string ORG_NAME { get; set; }
        public string FLAG_ORG { get; set; }
        public string FLAG_ROW { get; set; }
        public string UPLOAD_BY { get; set; }
        public Nullable<System.DateTime> UPLOAD_DATE { get; set; }
    }
}
