//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_T_PROMOTION_INVEST
    {
        public int DOC_PROM_PI_ID { get; set; }
        public Nullable<int> DOC_PROM_PS_ID { get; set; }
        public Nullable<int> DOC_PROM_PH_ID { get; set; }
        public string DOC_CODE { get; set; }
        public Nullable<int> DOC_VER { get; set; }
        public Nullable<int> DOC_REV { get; set; }
        public string COMP_CODE { get; set; }
        public string BRAND_CODE { get; set; }
        public string PROD_CODE { get; set; }
        public string PROD_SKU { get; set; }
        public string ACTIVITY_CODE { get; set; }
        public string INVEST_TYPE { get; set; }
        public Nullable<decimal> INVEST_VALUE { get; set; }
        public Nullable<decimal> INVEST_AMOUNT { get; set; }
        public string ACTIVITY_CODE_OTHER { get; set; }
        public string ACTIVITY_COMBINED_OTHER { get; set; }
        public Nullable<decimal> INCREMENT_SALE_INVEST { get; set; }
        public string INVEST_ACC_CODE { get; set; }
        public string FUND1_CODE { get; set; }
        public string FUND1_CENTER_CODE { get; set; }
        public string FUND1_AMOUNT { get; set; }
        public string FUND2_CODE { get; set; }
        public string FUND2_CENTER_CODE { get; set; }
        public Nullable<decimal> FUND2_AMOUNT { get; set; }
        public string REMARKS { get; set; }
        public string FLAG_ROW { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    
        public virtual TB_T_PROMOTION_SALE TB_T_PROMOTION_SALE { get; set; }
    }
}
