//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_T_FIXED_CONTRACT_H
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_T_FIXED_CONTRACT_H()
        {
            this.TB_T_FIXED_CONTRACT_D = new HashSet<TB_T_FIXED_CONTRACT_D>();
        }
    
        public int DOC_FCH_ID { get; set; }
        public string DOC_CODE { get; set; }
        public int DOC_VER { get; set; }
        public int DOC_REV { get; set; }
        public string CLIENT_CODE { get; set; }
        public string CUST_CODE { get; set; }
        public string CHANNEL_CODE { get; set; }
        public string COMP_CODE { get; set; }
        public string DOC_STATUS { get; set; }
        public string COMMENT { get; set; }
        public string FLAG_ROW { get; set; }
        public string REQUETER_ORG_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    
        public virtual TB_T_DOCUMENT TB_T_DOCUMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_T_FIXED_CONTRACT_D> TB_T_FIXED_CONTRACT_D { get; set; }
    }
}
