//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_T_FIXED_CONTRACT_D
    {
        public int DOC_FCH_ID { get; set; }
        public int DOC_FCD_ID { get; set; }
        public string DOC_CODE { get; set; }
        public string BRAND_CODE { get; set; }
        public string ACTIVITY_CODE { get; set; }
        public string CENTER_CODE { get; set; }
        public string ACC_CODE { get; set; }
        public string SIZE { get; set; }
        public string UOM { get; set; }
        public string PACK { get; set; }
        public string DATE_REF { get; set; }
        public string CONDITION_TYPE { get; set; }
        public string CONTRACT_CATE { get; set; }
        public string CONTRACT_DESC { get; set; }
        public Nullable<decimal> M01 { get; set; }
        public Nullable<decimal> M02 { get; set; }
        public Nullable<decimal> M03 { get; set; }
        public Nullable<decimal> M04 { get; set; }
        public Nullable<decimal> M05 { get; set; }
        public Nullable<decimal> M06 { get; set; }
        public Nullable<decimal> M07 { get; set; }
        public Nullable<decimal> M08 { get; set; }
        public Nullable<decimal> M09 { get; set; }
        public Nullable<decimal> M10 { get; set; }
        public Nullable<decimal> M11 { get; set; }
        public Nullable<decimal> M12 { get; set; }
        public string COMMENT { get; set; }
        public string FLAG_ROW { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    
        public virtual TB_T_DOCUMENT TB_T_DOCUMENT { get; set; }
    }
}
