//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_T_CREDIT_NOTE
    {
        public int CN_ID { get; set; }
        public Nullable<int> BILL_ID { get; set; }
        public Nullable<int> CN_NO { get; set; }
        public string CN_DESC { get; set; }
        public Nullable<int> QTY { get; set; }
        public Nullable<decimal> UNIT_PRICE { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string FLAG_ROW { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    
        public virtual TB_T_BILLING TB_T_BILLING { get; set; }
    }
}
