//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_T_PROMOTION_PLAN_D
    {
        public Nullable<int> DOC_PROPLH_ID { get; set; }
        public int DOC_PROPLD_ID { get; set; }
        public string DOC_CODE { get; set; }
        public string PROPLD_TYPE_CODE { get; set; }
        public string FLAG_ROW { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    
        public virtual TB_M_PROMOTION_PLAN_TYPE TB_M_PROMOTION_PLAN_TYPE { get; set; }
        public virtual TB_T_DOCUMENT TB_T_DOCUMENT { get; set; }
    }
}
