//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_T_DOCUMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_T_DOCUMENT()
        {
            this.TB_T_BUDGET_D = new HashSet<TB_T_BUDGET_D>();
            this.TB_T_BUDGET_H = new HashSet<TB_T_BUDGET_H>();
            this.TB_T_CLAIM_D = new HashSet<TB_T_CLAIM_D>();
            this.TB_T_CLAIM_H = new HashSet<TB_T_CLAIM_H>();
            this.TB_T_FIXED_CONTRACT_D = new HashSet<TB_T_FIXED_CONTRACT_D>();
            this.TB_T_FIXED_CONTRACT_H = new HashSet<TB_T_FIXED_CONTRACT_H>();
            this.TB_T_PROMOTION_PLAN_D = new HashSet<TB_T_PROMOTION_PLAN_D>();
            this.TB_T_PROMOTION_PLAN_H = new HashSet<TB_T_PROMOTION_PLAN_H>();
        }
    
        public string DOC_TYPE_CODE { get; set; }
        public string DOC_CODE { get; set; }
        public string DOC_VER { get; set; }
        public string DOC_REV { get; set; }
        public string DOC_MONTH { get; set; }
        public string DOC_YEAR { get; set; }
        public string DOC_STATUS { get; set; }
        public string FLOW_CURRENT { get; set; }
        public string FLOW_NEXT { get; set; }
        public string REQUESTER { get; set; }
    
        public virtual TB_M_DOCUMENT_TYPE TB_M_DOCUMENT_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_T_BUDGET_D> TB_T_BUDGET_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_T_BUDGET_H> TB_T_BUDGET_H { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_T_CLAIM_D> TB_T_CLAIM_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_T_CLAIM_H> TB_T_CLAIM_H { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_T_FIXED_CONTRACT_D> TB_T_FIXED_CONTRACT_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_T_FIXED_CONTRACT_H> TB_T_FIXED_CONTRACT_H { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_T_PROMOTION_PLAN_D> TB_T_PROMOTION_PLAN_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_T_PROMOTION_PLAN_H> TB_T_PROMOTION_PLAN_H { get; set; }
    }
}
