//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_T_PROMOTION_SALE
    {
        public int PROPL_SALE_ID { get; set; }
        public Nullable<int> PROPL_ID { get; set; }
    
        public virtual TB_T_PROMOTION_PLAN_H TB_T_PROMOTION_PLAN_H { get; set; }
    }
}
