//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_T_BUDGET
    {
        public int BG_ID { get; set; }
        public Nullable<int> DOC_ID { get; set; }
        public Nullable<int> BG_TYPE_ID { get; set; }
        public Nullable<int> BRAND_ID { get; set; }
        public string FLAG_ROW { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    
        public virtual TB_M_BUDGET_TYPE TB_M_BUDGET_TYPE { get; set; }
        public virtual TB_T_DOCUMENT TB_T_DOCUMENT { get; set; }
    }
}
