//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_T_BILLING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_T_BILLING()
        {
            this.TB_T_CREDIT_NOTE = new HashSet<TB_T_CREDIT_NOTE>();
            this.TB_T_DEBIT_NOTE = new HashSet<TB_T_DEBIT_NOTE>();
        }
    
        public int BILL_ID { get; set; }
        public string BILL_TYPE { get; set; }
        public string INV_DATE { get; set; }
        public string TAX_NO { get; set; }
        public int CUST_NAME { get; set; }
        public string CUST_ADDRESS { get; set; }
        public string FLAG_ROW { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_T_CREDIT_NOTE> TB_T_CREDIT_NOTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_T_DEBIT_NOTE> TB_T_DEBIT_NOTE { get; set; }
    }
}
