//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_T_PROMOTION_PLAN_H
    {
        public int DOC_PROPLH_ID { get; set; }
        public string DOC_CODE { get; set; }
        public string PROGP_CODE { get; set; }
        public string CLIENT_CODE { get; set; }
        public string CUST_CODE { get; set; }
        public string CHANNEL_CODE { get; set; }
        public string PROPL_CODE { get; set; }
        public string PROPL_NAME { get; set; }
        public Nullable<System.DateTime> PROPL_BEGIN { get; set; }
        public Nullable<System.DateTime> PROPL_END { get; set; }
        public string FLAG_ROW { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    
        public virtual TB_M_PROMOTION_GROUP TB_M_PROMOTION_GROUP { get; set; }
        public virtual TB_T_DOCUMENT TB_T_DOCUMENT { get; set; }
    }
}
