//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_T_PROMOTION_SALE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_T_PROMOTION_SALE()
        {
            this.TB_T_PROMOTION_INVEST = new HashSet<TB_T_PROMOTION_INVEST>();
        }
    
        public int DOC_PROM_PS_ID { get; set; }
        public Nullable<int> DOC_PROM_PH_ID { get; set; }
        public string DOC_CODE { get; set; }
        public Nullable<int> DOC_VER { get; set; }
        public Nullable<int> DOC_REV { get; set; }
        public string COMP_CODE { get; set; }
        public string BRAND_CODE { get; set; }
        public string PROD_CODE { get; set; }
        public string PROD_SKU { get; set; }
        public Nullable<decimal> PROD_LTP_EXCL_VAT { get; set; }
        public Nullable<decimal> NORM_PERC_DISC { get; set; }
        public Nullable<decimal> NORM_PERC_GP { get; set; }
        public Nullable<decimal> NORM_SHELF_PRICE { get; set; }
        public Nullable<decimal> PROMO_PERC_DISC { get; set; }
        public Nullable<decimal> PROMO_PERC_GP { get; set; }
        public Nullable<decimal> PROMO_SHELF_PRICE { get; set; }
        public Nullable<decimal> DEAL_GUIDE_LINE { get; set; }
        public Nullable<decimal> NET_INTO_STORE { get; set; }
        public Nullable<decimal> AVG_SALE { get; set; }
        public Nullable<decimal> AVG_VOLUME { get; set; }
        public Nullable<int> SALE_QTY { get; set; }
        public Nullable<decimal> SALE_VALUE_EXCL_VAT { get; set; }
        public string SALE_UOM { get; set; }
        public string DISC_TYPE { get; set; }
        public string FLAG_ROW { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    
        public virtual TB_T_PROMOTION_H TB_T_PROMOTION_H { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_T_PROMOTION_INVEST> TB_T_PROMOTION_INVEST { get; set; }
    }
}
