//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_WP_STATE_DIRECTION
    {
        public int WF_STATE_ID { get; set; }
        public int FLOW_ITEM_ID { get; set; }
        public string STATE_CODE { get; set; }
        public string FLOW_ITEM_CODE { get; set; }
        public string DIRECTION_CODE { get; set; }
        public string DIRECTION_NAME { get; set; }
        public Nullable<int> Sort { get; set; }
    
        public virtual TB_WM_FLOW_ITEM TB_WM_FLOW_ITEM { get; set; }
        public virtual TB_WM_WORKFLOW_STATE TB_WM_WORKFLOW_STATE { get; set; }
    }
}
