//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_WM_WORKFLOW_STATE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_WM_WORKFLOW_STATE()
        {
            this.TB_WM_WORKFLOW_STATE1 = new HashSet<TB_WM_WORKFLOW_STATE>();
            this.TB_WP_STATE_ACTOR = new HashSet<TB_WP_STATE_ACTOR>();
            this.TB_WP_STATE_DIRECTION = new HashSet<TB_WP_STATE_DIRECTION>();
        }
    
        public int WF_STATE_ID { get; set; }
        public Nullable<int> WF_STATE_PARENT_ID { get; set; }
        public int WF_ID { get; set; }
        public string WF_CODE { get; set; }
        public string STATE_CODE { get; set; }
        public string STATE_NAME { get; set; }
        public string STATE_DESC { get; set; }
        public string NOTI_SUBJECT { get; set; }
        public string NOTI_MESSAGE { get; set; }
        public Nullable<System.DateTime> EFF_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
    
        public virtual TB_WM_WORKFLOW TB_WM_WORKFLOW { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_WM_WORKFLOW_STATE> TB_WM_WORKFLOW_STATE1 { get; set; }
        public virtual TB_WM_WORKFLOW_STATE TB_WM_WORKFLOW_STATE2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_WP_STATE_ACTOR> TB_WP_STATE_ACTOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_WP_STATE_DIRECTION> TB_WP_STATE_DIRECTION { get; set; }
    }
}
