//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_WM_FLOW_ITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_WM_FLOW_ITEM()
        {
            this.TB_WP_STATE_DIRECTION = new HashSet<TB_WP_STATE_DIRECTION>();
        }
    
        public int FLOW_ITEM_ID { get; set; }
        public string FLOW_ITEM_CODE { get; set; }
        public string FLOW_ITEM_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_WP_STATE_DIRECTION> TB_WP_STATE_DIRECTION { get; set; }
    }
}
