//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_WM_OPERATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_WM_OPERATION()
        {
            this.TB_WP_STATE_ACTOR = new HashSet<TB_WP_STATE_ACTOR>();
        }
    
        public int OPERATOR_ID { get; set; }
        public string OPERATOR_CODE { get; set; }
        public string OPERATOR_DESC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_WP_STATE_ACTOR> TB_WP_STATE_ACTOR { get; set; }
    }
}
