//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_WP_STATE_ACTOR
    {
        public int WF_STATE_ID { get; set; }
        public int ACTOR_ID { get; set; }
        public int OPERATOR_ID { get; set; }
        public string WF_STATE_CODE { get; set; }
        public string ACTOR_CODE { get; set; }
        public string OPERATOR_CODE { get; set; }
        public string CONTACT_TYPE { get; set; }
        public Nullable<decimal> LIMIT_VALUE { get; set; }
    
        public virtual TB_WM_OPERATION TB_WM_OPERATION { get; set; }
        public virtual TB_WM_WORKFLOW_STATE TB_WM_WORKFLOW_STATE { get; set; }
    }
}
