//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradeInvesment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TradeInvesment()
        {
            this.FixedContracts = new HashSet<FixedContract>();
        }
    
        public Nullable<int> AccountId { get; set; }
        public int ChannelId { get; set; }
        public int CustomerId { get; set; }
        public string TradeActivity { get; set; }
        public int TradeInvesmentId { get; set; }
        public string TradeCode { get; set; }
        public string TradeName { get; set; }
        public string SubGroup { get; set; }
        public string DataSource { get; set; }
        public bool IsFixedContract { get; set; }
        public bool Deductable { get; set; }
        public string ToleranceLevel { get; set; }
        public Nullable<decimal> ToleranceLower { get; set; }
        public Nullable<decimal> ToleranceUpper { get; set; }
        public string CostElement { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Channel Channel { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FixedContract> FixedContracts { get; set; }
        public virtual GLAccount GLAccount { get; set; }
    }
}
