//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradeActivity
    {
        public int AccountId { get; set; }
        public int TradeActivityId { get; set; }
        public string ActivityType { get; set; }
        public string ActivityCode { get; set; }
        public string ActivityName { get; set; }
        public string FixedContract { get; set; }
        public string Deductable { get; set; }
        public string SaleInTHBCS { get; set; }
        public string SaleInGrossSale { get; set; }
        public string SaleInNotSale { get; set; }
        public string SaleOutTHBCS { get; set; }
        public string SaleOutGrossSale { get; set; }
        public string SaleOutNotSale { get; set; }
        public string NotRelateSaleAbsAmt { get; set; }
        public string Remark { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Valuable { get; set; }
    }
}
