//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFCA.APT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowState
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkflowState()
        {
            this.ActorStates = new HashSet<ActorState>();
            this.StateFlowItems = new HashSet<StateFlowItem>();
            this.StateProcesses = new HashSet<StateProcess>();
            this.WorkflowState1 = new HashSet<WorkflowState>();
        }
    
        public int WorkflowStateId { get; set; }
        public Nullable<int> PreviousStateId { get; set; }
        public int WorkflowId { get; set; }
        public string StateName { get; set; }
        public string StateDesc { get; set; }
        public string NotifySubject { get; set; }
        public string NotifyMessage { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActorState> ActorStates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StateFlowItem> StateFlowItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StateProcess> StateProcesses { get; set; }
        public virtual Workflow Workflow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkflowState> WorkflowState1 { get; set; }
        public virtual WorkflowState WorkflowState2 { get; set; }
    }
}
