CREATE TABLE [dbo].[TB_M_CLIENT](
	[CLIENT_ID] [int] IDENTITY(1,1) NOT NULL,
	[CLIENT_CODE] [varchar](50) NOT NULL,
	[CLIENT_NAME] [varchar](100) NULL,
	[CLIENT_DESC] [varchar](max) NULL,
	[FLAG_ROW] [varchar](1) NULL,
	[CREATED_BY] [dbo].[T_NAME] NOT NULL,
	[CREATED_DATE] [dbo].[T_AUDIT_DATE] NOT NULL,
	[UPDATED_BY] [dbo].[T_NAME] NULL,
	[UPDATED_DATE] [dbo].[T_AUDIT_DATE] NULL
 CONSTRAINT [PK_TB_M_CLIENT] PRIMARY KEY CLUSTERED 
(
	[CLIENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

