CREATE TABLE [dbo].[TB_M_ORGANIZATION](
	[ORG_CODE] [T_CODE],
	[REPORT_TO] [T_CODE] NULL,
	[COMP_CODE] [T_CODE] NULL,
	[HIERACHY_ID] [T_DESC],
	[ORG_NAME] T_NAME,
	[ORG_ABBR] [varchar](100) NULL,
	[ORG_DESC] [T_DESC],
	[FLAG_ORG] [varchar](1) NULL,
	[FLAG_ROW] [varchar](1) NULL,
	[CREATED_BY] [varchar](100) NOT NULL,
	[CREATED_DATE] [datetime2](7) NOT NULL,
	[UPDATED_BY] [varchar](100) NULL,
	[UPDATED_DATE] [datetime2](7) NULL,
 CONSTRAINT [PK_TB_M_ORGANIZATION_1] PRIMARY KEY CLUSTERED 
(
	[ORG_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[TB_M_ORGANIZATION] ADD  CONSTRAINT [DF_TB_M_ORGANIZATION_FLAG_ROW]  DEFAULT ('S') FOR [FLAG_ROW]
GO

ALTER TABLE [dbo].[TB_M_ORGANIZATION]  WITH CHECK ADD  CONSTRAINT [FK_TB_M_ORGANIZATION_TB_M_COMPANY] FOREIGN KEY([COMP_CODE])
REFERENCES [dbo].[TB_M_COMPANY] ([COMP_CODE])
GO

ALTER TABLE [dbo].[TB_M_ORGANIZATION] CHECK CONSTRAINT [FK_TB_M_ORGANIZATION_TB_M_COMPANY]
GO

ALTER TABLE [dbo].[TB_M_ORGANIZATION]  WITH CHECK ADD  CONSTRAINT [FK_TB_M_ORGANIZATION_TB_M_ORGANIZATION] FOREIGN KEY([REPORT_TO])
REFERENCES [dbo].[TB_M_ORGANIZATION] ([ORG_CODE])
GO

ALTER TABLE [dbo].[TB_M_ORGANIZATION] CHECK CONSTRAINT [FK_TB_M_ORGANIZATION_TB_M_ORGANIZATION]
GO

