CREATE TABLE [dbo].[TB_M_COMPANY](
	[COMP_CODE] [varchar](50) NOT NULL,
	[COMP_NAME] [varchar](100) NULL,
	[ADDRESS] [varchar](max) NULL,
	[FLAG_ROW] [varchar](1) NULL,
	[CREATED_BY] [varchar](100) NOT NULL,
	[CREATED_DATE] [datetime2](7) NOT NULL,
	[UPDATED_BY] [varchar](100) NULL,
	[UPDATED_DATE] [datetime2](7) NULL,
 CONSTRAINT [PK_TB_M_COMPANY_1] PRIMARY KEY CLUSTERED 
(
	[COMP_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[TB_M_COMPANY] ADD  CONSTRAINT [DF_TB_M_COMPANY_FLAG_ROW]  DEFAULT ('S') FOR [FLAG_ROW]
GO

