CREATE TABLE [dbo].[TB_P_EMP_ORG](
	[ORG_TYPE] [varchar](1) NULL,
	[EMP_CODE] [varchar](50) NOT NULL,
	[ORG_CODE] [varchar](50) NOT NULL,
	[EFF_FROM] [date] NULL,
	[EFF_TO] [date] NULL,
	[CREATED_BY] [varchar](100) NOT NULL,
	[CREATED_DATE] [datetime2](7) NOT NULL,
	[UPDATED_BY] [varchar](100) NULL,
	[UPDATED_DATE] [datetime2](7) NULL,
 CONSTRAINT [PK_TB_P_EMP_ORG] PRIMARY KEY CLUSTERED 
(
	[EMP_CODE] ASC,
	[ORG_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TB_P_EMP_ORG] ADD  CONSTRAINT [DF_TB_P_EMP_ORG_EFF_FROM]  DEFAULT (sysdatetime()) FOR [EFF_FROM]
GO

ALTER TABLE [dbo].[TB_P_EMP_ORG] ADD  CONSTRAINT [DF_TB_P_EMP_ORG_EFF_TO]  DEFAULT ('9999-12-31') FOR [EFF_TO]
GO

ALTER TABLE [dbo].[TB_P_EMP_ORG]  WITH CHECK ADD  CONSTRAINT [FK_TB_P_EMP_ORG_TB_M_EMPLOYEE] FOREIGN KEY([EMP_CODE])
REFERENCES [dbo].[TB_M_EMPLOYEE] ([EMP_CODE])
GO

ALTER TABLE [dbo].[TB_P_EMP_ORG] CHECK CONSTRAINT [FK_TB_P_EMP_ORG_TB_M_EMPLOYEE]
GO

ALTER TABLE [dbo].[TB_P_EMP_ORG]  WITH CHECK ADD  CONSTRAINT [FK_TB_P_EMP_ORG_TB_M_ORGANIZATION] FOREIGN KEY([ORG_CODE])
REFERENCES [dbo].[TB_M_ORGANIZATION] ([ORG_CODE])
GO

ALTER TABLE [dbo].[TB_P_EMP_ORG] CHECK CONSTRAINT [FK_TB_P_EMP_ORG_TB_M_ORGANIZATION]
GO


