CREATE TABLE [dbo].[TB_S_CUST_PRODUCT](
	[CUST_CODE] [dbo].[T_CODE] NULL,
	[ORG_CODE] [dbo].[T_CODE] NULL,
	[DIV_CODE] [dbo].[T_CODE] NULL,
	[EMIS_CODE] [dbo].[T_CODE] NULL,
	[FLAG_ROW] [dbo].[T_FLAG] NULL,
	[UPLOAD_BY] [dbo].[T_NAME] NULL,
	[UPLOAD_DATE] [dbo].[T_DATETIME] NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TB_S_CUST_PRODUCT] ADD  CONSTRAINT [DF_TB_S_CUST_PRODUCT_UPLOAD_BY]  DEFAULT ('System') FOR [UPLOAD_BY]
GO

ALTER TABLE [dbo].[TB_S_CUST_PRODUCT] ADD  CONSTRAINT [DF_TB_S_CUST_PRODUCT_UPLOAD_DATE]  DEFAULT (sysdatetime()) FOR [UPLOAD_DATE]
GO
