CREATE TABLE [dbo].[TB_S_BRAND_PRODUCT](
	[BRAND_CODE] [dbo].[T_CODE] NULL,
	[BRAND_NAME] [dbo].[T_NAME] NULL,
	[BRAND_DESC] [dbo].[T_DESC] NULL,
	[PROD_CODE] [dbo].[T_CODE] NULL,
	[PROD_NAME] [dbo].[T_NAME] NULL,
	[MAT_CODE] [dbo].[T_CODE] NULL,
	[MAT_GROUP] [dbo].[T_NAME] NULL,
	[MAT_GROUP_DESC] [dbo].[T_DESC] NULL,
	[MAT_GROUP1] [dbo].[T_NAME] NULL,
	[MAT_GROUP1_DESC] [dbo].[T_DESC] NULL,
	[MAT_GROUP2] [dbo].[T_NAME] NULL,
	[MAT_GROUP2_DESC] [dbo].[T_DESC] NULL,
	[MAT_GROUP3] [dbo].[T_NAME] NULL,
	[MAT_GROUP3_DESC] [dbo].[T_DESC] NULL,
	[MAT_GROUP4] [dbo].[T_NAME] NULL,
	[MAT_GROUP4_DESC] [dbo].[T_DESC] NULL,
	[FORMULA] [dbo].[T_NAME] NULL,
	[PACK] [int] NULL,
	[PACK_DESC] [dbo].[T_DESC] NULL,
	[SIZE] [int] NULL,
	[UOM_SIZE] [varchar](50) NULL,
	[UOM_SALE] [nvarchar](50) NULL,
	[UNIT_CODE] [varchar](50) NULL,
	[CONV_FCL] [numeric](18, 0) NULL,
	[CONV_L] [numeric](18, 0) NULL,
	[FLAG_ROW] [dbo].[T_FLAG] NULL,
	[UPLOAD_BY] [dbo].[T_NAME] NULL,
	[UPLOAD_DATE] [dbo].[T_DATETIME] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[TB_S_BRAND_PRODUCT] ADD  CONSTRAINT [DF_TB_S_BRAND_PRODUCT_UPLOAD_BY]  DEFAULT ('System') FOR [UPLOAD_BY]
GO

ALTER TABLE [dbo].[TB_S_BRAND_PRODUCT] ADD  CONSTRAINT [DF_TB_S_BRAND_PRODUCT_UPLOAD_DATE]  DEFAULT (sysdatetime()) FOR [UPLOAD_DATE]
GO
