CREATE TABLE [dbo].[TB_S_EMPLOYEE](
	[EMP_CODE] [dbo].[T_CODE] NOT NULL,
	[NAME_FIRST] [dbo].[T_NAME] NULL,
	[NAME_LAST] [dbo].[T_NAME] NULL,
	[EMAIL] [dbo].[T_NAME] NULL,
	[ORG_CODE] [dbo].[T_CODE] NULL,
	[ORG_NAME] [dbo].[T_NAME] NULL,
	[COMP_CODE] [dbo].[T_CODE] NULL,
	[COMP_NAME] [dbo].[T_NAME] NULL,
	[FLAG_ROW] [varchar](1) NULL,
	[UPLOAD_BY] [dbo].[T_NAME] NULL,
	[UPLOAD_DATE] [datetime2](7) NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TB_S_EMPLOYEE] ADD  CONSTRAINT [DF_TB_S_EMPLOYEE_FLAG_ROW]  DEFAULT ('I') FOR [FLAG_ROW]
GO

ALTER TABLE [dbo].[TB_S_EMPLOYEE] ADD  CONSTRAINT [DF_TB_S_EMPLOYEE_UPLOAD_BY]  DEFAULT ('System') FOR [UPLOAD_BY]
GO

ALTER TABLE [dbo].[TB_S_EMPLOYEE] ADD  CONSTRAINT [DF_TB_S_EMPLOYEE_UPLOAD_DATE]  DEFAULT (sysdatetime()) FOR [UPLOAD_DATE]
GO


