CREATE TABLE [dbo].[TB_T_FIXED_CONTRACT_H](
	[DOC_FCH_ID] [int] IDENTITY(1,1) NOT NULL,
	[DOC_CODE] [dbo].[T_CODE] NOT NULL,
	[DOC_VER] [int] NOT NULL,
	[DOC_REV] [int] NOT NULL,
	[CLIENT_CODE] [dbo].[T_CODE] NULL,
	[CUST_CODE] [dbo].[T_CODE] NULL,
	[CHANNEL_CODE] [dbo].[T_CODE] NULL,
	[COMP_CODE] [dbo].[T_CODE] NULL,
	[DOC_STATUS] [dbo].[T_CODE] NULL,
	[COMMENT] [dbo].[T_DESC] NULL,
	[FLAG_ROW] [dbo].[T_FLAG] NULL,
	[REQUETER_ORG_CODE] [dbo].[T_CODE] NULL,
	[CREATED_BY] [dbo].[T_NAME] NULL,
	[CREATED_DATE] [dbo].[T_DATETIME] NULL,
	[UPDATED_BY] [dbo].[T_NAME] NULL,
	[UPDATED_DATE] [dbo].[T_DATETIME] NULL,
 CONSTRAINT [PK_TB_T_FIXED_CONTRACT_H] PRIMARY KEY CLUSTERED 
(
	[DOC_FCH_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[TB_T_FIXED_CONTRACT_H] ADD  CONSTRAINT [DF_TB_T_FIXED_CONTRACT_H_CREATED_BY]  DEFAULT ('System') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[TB_T_FIXED_CONTRACT_H] ADD  CONSTRAINT [DF_TB_T_FIXED_CONTRACT_H_CREATED_DATE]  DEFAULT (sysdatetime()) FOR [CREATED_DATE]
GO
