CREATE TABLE [dbo].[TB_T_PROMOTION_H](
	[DOC_PROM_PH_ID] [int] IDENTITY(1,1) NOT NULL,
	[DOC_CODE] [dbo].[T_CODE] NULL,
	[DOC_VER] [int] NULL,
	[DOC_REV] [int] NULL,
	[DOC_STATUS] [dbo].[T_CODE] NULL,
	[PROMO_NAME] [dbo].[T_NAME] NULL,
	[PROMO_START] [date] NULL,
	[PROMO_END] [date] NULL,
	[BUYING_START] [date] NULL,
	[BUYING_END] [date] NULL,
	[CLIENT_CODE] [dbo].[T_CODE] NULL,
	[CHANNEL_CODE] [dbo].[T_CODE] NULL,
	[CUST_CODE] [dbo].[T_CODE] NULL,
	[CUST_SEGMENT] [dbo].[T_CODE] NULL,
	[TOTAL_EST_SALE] [dbo].[T_MONEY] NULL,
	[TOTAL_EST_INVEST] [dbo].[T_MONEY] NULL,
	[SALE_VS_INVEST] [dbo].[T_MONEY] NULL,
	[COMMENT] [dbo].[T_DESC] NULL,
	[FLAG_ROW] [dbo].[T_FLAG] NULL,
	[CREATED_BY] [dbo].[T_NAME] NULL,
	[CREATED_DATE] [dbo].[T_DATETIME] NULL,
	[UPDATED_BY] [dbo].[T_NAME] NULL,
	[UPDATED_DATE] [dbo].[T_DATETIME] NULL,
 CONSTRAINT [PK_TB_T_PROMOTION_H] PRIMARY KEY CLUSTERED 
(
	[DOC_PROM_PH_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]